# Generated by Django 4.2.4 on 2023-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2023-09-07 16:05'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2023-09-07 16:05'),
        ),
    ]
